### ISSUE TITLE
Monitor several input files

### ISSUE THREAD

**Issue by svenha** [urbanware-org/salomon#11]
This is a feature request to make -i file1 -i file2 work on two files.

**Comment by urbanware-org** [comment]
Do you mean read out two files and into one output?

**Comment by urbanware-org** [comment]
> Do you mean read out two files and "combine" them into one output?

If so, you may have a look at this branch: https://github.com/urbanware-org/salomon/tree/multiple_files

This is just experimental so far. For now, it works when using monitoring mode, only. I will deliver a version that will also allow to give multiple files when using the analyze mode as soon as possible.

It should work this way now:
```bash
./salomon.sh -i file1 -i file2 -c foobar.cfg
```

**Comment by svenha** [comment]
Thanks; very helpful extension.

**Comment by urbanware-org** [comment]
You're welcome! Let me know if there are any issues.

**Comment by urbanware-org** [comment]
**Added** in version **1.8.2**.
